name: Deploy

on:
  release:
    types: [created]


jobs:
  build:
    # if: ${{ github.repository == 'hyochan/flat_list' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true
